config/routes.rb
Facturacion::Application.routes.draw do
 

  resources :proveedors

  get "itemfacturas/index"

  get "itemfacturas/show"

  get "itemfacturas/new"

  get "itemfacturas/create"

  get "itemfacturas/edit"

  get "itemfacturas/update"

  get "itemfacturas/destroy"

  get "productos/index"

  get "productos/show"

  get "productos/new"

  get "productos/create"

  get "productos/edit"

  get "productos/update"

  get "productos/destroy"

  get "facturas/index"

  get "facturas/show"

  get "facturas/new"

  get "facturas/create"

  get "facturas/edit"

  get "facturas/update"

  get "facturas/destroy"

  get "clientes/index"

  get "clientes/show"

  get "clientes/new"

  get "clientes/create"

  get "clientes/edit"

  get "clientes/update"

  get "clientes/destroy"

  get "facturas/autocomplete_cliente_cedula"

  resources :clientes
  resources :facturas
  resources :itemfacturas
  resources :productos

  resources :facturas do
    get :autocomplete_cliente_cedula, :on => :collection
  end

  

  root :to => 'productos#index'

end

app/models/cliente.rb
# encoding: utf-8
class Cliente < ActiveRecord::Base
  attr_accessible :cedula, :direccion, :nombres, :telefono
  validates :cedula, :direccion, :nombres, :telefono, :presence => true 
  validates :cedula, :uniqueness => { :message => "Cedula ya en uso" }
  validates :cedula, :numericality => {:only_integer => true}
  validates :telefono, :numericality => {:only_integer => true}
  validates :cedula, :length => { :in => 10..13 }
  validate :validate_identificacion


  has_many :facturas

  def self.search(search)
  	if search
  		where('nombres LIKE ?', "%#{search}%")
  	else
  		scoped
  	end
  	
  end
  
    def validate_identificacion
      tipo_numero_de_identificacion = nil
      valido = false
      productos = []
      unless (10..13) === self.numero_de_identificacion.size
        errors.add(:numero_de_identificacion, "longitud incorrecta")
      end
      provincias = 22
      codigo_provincia = self.numero_de_identificacion[0,2].to_i
      if codigo_provincia < 1 or codigo_provincia > provincias
        errors.add(:numero_de_identificacion, "código de provincia incorrecto")
      end
      # tercer digito:
      #     9    -> sociedades privadas o extranjeras
      #     6    -> sociedades publicas
      #     0..6 -> personas naturales
      tercer_digito = self.numero_de_identificacion[2].to_i
      if (7..8) === tercer_digito
        errors.add(:numero_de_identificacion, "tercer dígito inválido")
      end
      if tercer_digito == 9
        tipo_numero_de_identificacion = "Sociedad privada o extranjera"
      else
        if tercer_digito == 6
          tipo_numero_de_identificacion = "Sociedad pública"
        else
          if tercer_digito < 6
            tipo_numero_de_identificacion  = "Persona natural"
          end
        end
      end

      # para personas naturales:
      if tercer_digito < 6
        modulo = 10
        p = 2
        verificador = self.numero_de_identificacion[9].to_i
        for i in self.numero_de_identificacion[0,9].split('')
          producto = i.to_i * p
          if producto >= 10 then producto -= 9 end
          productos.push producto
          if p == 2 then p = 1 else p = 2 end
        end
      end
      
      # para sociedades públicas:
      if tercer_digito == 6
        verificador = self.numero_de_identificacion[8].to_i
        modulo = 11
        multiplicadores = [ 3, 2, 7, 6, 5, 4, 3, 2 ]
        for i in (0..7).to_a
          productos[i] = self.numero_de_identificacion[i].to_i * multiplicadores[i]
        end
        productos[8] = 0
      end

      # para entidades privadas:
      if tercer_digito == 9
        verificador = self.numero_de_identificacion[9].to_i
        modulo = 11
        multiplicadores = [ 4, 3, 2, 7, 6, 5, 4, 3, 2 ]
        for i in (0..8).to_a
          productos[i] = self.numero_de_identificacion[i].to_i * multiplicadores[i]
        end
      end

      suma = 0
      for i in productos
        suma += i
        residuo = suma % modulo
        digito_verificador = if residuo == 0 then 0 else modulo - residuo end
      end

      # sociedades públicas:
      if tercer_digito == 6
        unless self.numero_de_identificacion[9,4] == "0001"
          errors.add(:numero_de_identificacion, "RUC de empresa del sector público debe terminar en 0001")
        end
        valido = digito_verificador == verificador
      end
      
      # entidades privadas:
      if tercer_digito == 9
        unless self.numero_de_identificacion[10,3] == "001"
          errors.add(:numero_de_identificacion, "RUC de entidad privada debe terminar en 001")
        end
        valido = (digito_verificador == verificador)
      end

      # personas naturales:
      if tercer_digito < 6
        if self.numero_de_identificacion.size > 10 and self.numero_de_identificacion[10,3] != "001"
          errors.add(:numero_de_identificacion, "RUC de persona natural debe terminar en 001")
        end
        valido = (digito_verificador == verificador)
      end

      errors.add(:numero_de_identificacion, "cédula no válida") if valido == false
    end

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
     respond_to do |format|
        format.html {    
        presentacion
        }
       format.js{
        presentacion       
      }
        format.json { 
          @clientes = Cliente.where("cedula like ?", "%#{params[:term]}%")
          @clientes = @clientes.map do |cliente|
            {
              :id => cliente.id,
              :label => cliente.cedula,
              :value => cliente.cedula,
              :nombres => cliente.nombres,
              :direccion => cliente.direccion,
              :telefono => cliente.telefono
            }
          end
          render :json => @clientes 
        }
     end
  end


  def show
    @cliente = Cliente.find(params[:id])
  end

  def new
    @cliente = Cliente.new
  end

  def create
    @cliente = Cliente.new(params[:cliente])
    if @cliente.save
      redirect_to clientes_path, :notice => "Cliente guardado"
    else
      render "new"
    end
  end

  def edit
    @cliente = Cliente.find(params[:id])
  end

  def update
    @cliente= Cliente.find(params[:id])
  
  if @cliente.update_attributes(params[:cliente]) 
    redirect_to clientes_path, :notice => "Cliente actualizado"
  else
    render "edit"
  end
  end

  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy
    redirect_to clientes_path, :notice => "Cliente eliminado"
  end
  
  private

  def sort_column
    Cliente.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def presentacion
    @clientes = Cliente.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 10)
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
	
end

app/views/clientes/_clientes.html.erb
<%= hidden_field_tag :direction, params[:direction]%>
<%= hidden_field_tag :sort, params[:sort]%>
<table class="table table-striped">
    <tr>
      <th><%=sortable "cedula"%></th>
      <th><%=sortable "nombres" %></th>
      <th><%=sortable  "direccion" %></th>
      <th><%=sortable  "telefono" %></th>
      <th>Acciones</th>
    </tr>
    <% @clientes.each do |cliente| %>
    <tr>
      <td><%= cliente.cedula %></td>
      <td><%= cliente.nombres %></td>
      <td><%= cliente.direccion %></td>
      <td><%= cliente.telefono %></td>
      <td><%= link_to "Mostrar",  {:action => "show", :id => cliente}, :class => 'btn btn-mini btn-info' %> | <%= link_to "Editar", edit_cliente_path(cliente),:class => 'btn btn-mini' %> | 
<%= link_to "Borrar", cliente, :confirm => "Estas seguro?", :method => :delete, :class => 'btn btn-mini btn-danger' %></td>
    </tr>
    <% end %>
  </table>
  <%= will_paginate @clientes%>

app/views/clientes/_form.html.erb
<%= form_for @cliente do |f| %>
	<% if @cliente.errors.any? %>
		<h2>Errores:</h2>	
		<ul>
			<% @cliente.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
<br>
	<%= f.label :cedula %>
	<%= f.text_field :cedula, :required => true%>
	<br />
	<%= f.label :nombres %>
	<%= f.text_field :nombres, :required => true  %>
	<br />
	<%= f.label :direccion %>
	<%= f.text_field :direccion, :required => true  %>
	<br />
	<%= f.label :telefono %>
	<%= f.telephone_field :telefono, :required => true  %>
<p>
	<%if @cliente.new_record?%>
		<%= f.submit "Crear Cliente", :class => "btn btn-success" %>
	<%else%>
		<%= f.submit "Actualizar Cliente", :class => "btn btn-success" %>
	<%end%>
</p>
<% end %>

app/views/clientes/edit.html.erb
<h1>Clientes</h1>
<h2>Editar Cliente</h2>
 
<%= render 'form' %>

app/views/clientes/index.html.erb
<h1>Clientes</h1>
<h2>Listado clientes</h2>

<%= form_tag clientes_path, :method => 'get', :id => "clientes_search", :remote => true do%>
  <p>
  <%= text_field_tag :search, params[:search], :placeholder => "Buscar por nombre"%>
   </p>
   <div id="clientes"><%= render 'clientes' %></div>
<%end%>
<p><%= link_to "Agregar nuevo cliente", new_cliente_path,:class => 'btn btn-primary'  %></p> 

app/views/clientes/index.js.erb
$("#clientes").html("<%= escape_javascript(render("clientes")) %>");

app/views/clientes/new.html.erb
<h1>Clientes</h1>
<h2>Nuevo cliente</h2>
 
<%= render 'form' %>

app/views/clientes/show.html.erb
<h1>Clientes</h1>
<h2>Mostrar cliente</h2>

<div class="info_title">Cédula:</div>
	<div class="info_content"><%=@cliente.cedula%></div>
<div class="info_title">Nombres:</div>
	<div class="info_content"><%=@cliente.nombres%></div>
<div class="info_title">Dirección:</div>
	<div class="info_content"><%=@cliente.direccion%></div>
<div class="info_title">Teléfono:</div>
	<div class="info_content"><%=@cliente.telefono%></div>


<%= link_to "Regresar a la lista", { :controller => :clientes}, :class => "btn btn-inverse"%>