config/routes.rb
Facturacion::Application.routes.draw do
 

  resources :proveedors

  get "itemfacturas/index"

  get "itemfacturas/show"

  get "itemfacturas/new"

  get "itemfacturas/create"

  get "itemfacturas/edit"

  get "itemfacturas/update"

  get "itemfacturas/destroy"

  get "productos/index"

  get "productos/show"

  get "productos/new"

  get "productos/create"

  get "productos/edit"

  get "productos/update"

  get "productos/destroy"

  get "facturas/index"

  get "facturas/show"

  get "facturas/new"

  get "facturas/create"

  get "facturas/edit"

  get "facturas/update"

  get "facturas/destroy"

  get "clientes/index"

  get "clientes/show"

  get "clientes/new"

  get "clientes/create"

  get "clientes/edit"

  get "clientes/update"

  get "clientes/destroy"

  get "facturas/autocomplete_cliente_cedula"

  resources :clientes
  resources :facturas
  resources :itemfacturas
  resources :productos

  resources :facturas do
    get :autocomplete_cliente_cedula, :on => :collection
  end

  

  root :to => 'productos#index'

end

app/models/proveedor.rb
# encoding: utf-8
class Proveedor < ActiveRecord::Base
  attr_accessible :cedula, :direccion, :nombres, :telefono
  has_many :productos

  validates :cedula, :direccion, :nombres, :telefono, :presence => true 
  validates :cedula, :uniqueness => { :message => "Cedula ya en uso" }
  validates :cedula, :numericality => {:only_integer => true}
  validates :telefono, :numericality => {:only_integer => true}
  validates :cedula, :length => { :in => 10..13 }
  validate :verify_cedula

  def verify_cedula
    autoverifier = self.cedula[ self.cedula.size - 1 ].to_i
    index = sum = 0
    self.cedula.chars { |char|
       break if index == self.cedula.size - 1
       number = char.to_i
       coef = index.even? ? 2 : 1
       product = number * coef
       product -= 9 if product > 9
       sum += product
       index += 1
   }
   remainder = sum % 10
   booleano =  10 - remainder == autoverifier
  errors.add(:cedula, "Cédula no válida") if booleano == false
end
end

app/controllers/proveedors_controller.rb
class ProveedorsController < ApplicationController
  # GET /proveedors
  # GET /proveedors.json
  def index

    respond_to do |format|
      format.html{
            @proveedors = Proveedor.all
          }
      format.json { 
          @proveedors = Proveedor.where("nombres like ?", "%#{params[:term]}%")
          @proveedors = @proveedors.map do |proveedor|
            {
              :id => proveedor.id,
              :label => proveedor.nombres,
              :value => proveedor.nombres
            }
          end
          render :json => @proveedors 
        }
    end
  end

  # GET /proveedors/1
  # GET /proveedors/1.json
  def show
    @proveedor = Proveedor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proveedor }
    end
  end

  # GET /proveedors/new
  # GET /proveedors/new.json
  def new
    @proveedor = Proveedor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proveedor }
    end
  end

  # GET /proveedors/1/edit
  def edit
    @proveedor = Proveedor.find(params[:id])
  end

  # POST /proveedors
  # POST /proveedors.json
  def create
    @proveedor = Proveedor.new(params[:proveedor])

    respond_to do |format|
      if @proveedor.save
        format.html { redirect_to @proveedor, notice: 'Proveedor was successfully created.' }
        format.json { render json: @proveedor, status: :created, location: @proveedor }
      else
        format.html { render action: "new" }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proveedors/1
  # PUT /proveedors/1.json
  def update
    @proveedor = Proveedor.find(params[:id])

    respond_to do |format|
      if @proveedor.update_attributes(params[:proveedor])
        format.html { redirect_to @proveedor, notice: 'Proveedor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proveedor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proveedors/1
  # DELETE /proveedors/1.json
  def destroy
    @proveedor = Proveedor.find(params[:id])
    @proveedor.destroy

    respond_to do |format|
      format.html { redirect_to proveedors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proveedors_helper.rb
module ProveedorsHelper
end

app/views/proveedors/_form.html.erb
<%= form_for(@proveedor) do |f| %>
  <% if @proveedor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proveedor.errors.count, "error") %> prohibited this proveedor from being saved:</h2>

      <ul>
      <% @proveedor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :cedula %>
    <%= f.text_field :cedula, :required => true %>
  </div>
  <div class="field">
    <%= f.label :nombres %>
    <%= f.text_field :nombres, :required => true %>
  </div>
  <div class="field">
    <%= f.label :direccion %>
    <%= f.text_field :direccion, :required => true %>
  </div>
  <div class="field">
    <%= f.label :telefono %>
    <%= f.text_field :telefono, :required => true %>
  </div>
  <div class="actions">
<%if @proveedor.new_record?%>
    <%= f.submit "Crear Proveedor", :class => "btn btn-success" %>
  <%else%>
    <%= f.submit "Actualizar Proveedor", :class => "btn btn-success" %>
  <%end%>  </div>
<% end %>

app/views/proveedors/edit.html.erb
<h1>Proveedores</h1>
<h2>Editar Proveedores</h2>

<%= render 'form' %>

app/views/proveedors/index.html.erb
<h1>Proveedores</h1>
<h2>Listado proveedores</h2>


<table class="table table-striped">
  <tr>
    <th>Cedula</th>
    <th>Nombres</th>
    <th>Direccion</th>
    <th>Telefono</th>
    <th>Acciones</th>
  </tr>

<% @proveedors.each do |proveedor| %>
  <tr>
    <td><%= proveedor.cedula %></td>
    <td><%= proveedor.nombres %></td>
    <td><%= proveedor.direccion %></td>
    <td><%= proveedor.telefono %></td>
<td><%= link_to "Mostrar",  {:action => "show", :id => proveedor}, :class => 'btn btn-mini btn-info' %> | <%= link_to "Editar", edit_proveedor_path(proveedor),:class => 'btn btn-mini' %> | 
<%= link_to "Borrar", proveedor, :confirm => "Estas seguro?", :method => :delete, :class => 'btn btn-mini btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />
<p><%= link_to "Agregar nuevo proveedor", new_proveedor_path,:class => 'btn btn-primary'  %></p> 

app/views/proveedors/new.html.erb
<h1>Proveedor</h1>
<h2>Nuevo proveedor</h2>

<%= render 'form' %>

app/views/proveedors/show.html.erb
<h1>Proveedores</h1>
<h2>Mostrar proveedor</h2>

<div class="info_title">Cédula:</div>
	<div class="info_content"><%=@proveedor.cedula%></div>
<div class="info_title">Nombres:</div>
	<div class="info_content"><%=@proveedor.nombres%></div>
<div class="info_title">Dirección:</div>
	<div class="info_content"><%=@proveedor.direccion%></div>
<div class="info_title">Teléfono:</div>
	<div class="info_content"><%=@proveedor.telefono%></div>
<div class="info_title">Productos:</div>
	<% @proveedor.productos.each do |producto| %>
	<div class="info_content"><%=producto.descripcion%></div>
	<%end%>
<%= link_to "Regresar a la lista", { :controller => :proveedors}, :class => "btn btn-inverse"%>