config/routes.rb
Facturacion::Application.routes.draw do
 

  resources :proveedors

  get "itemfacturas/index"

  get "itemfacturas/show"

  get "itemfacturas/new"

  get "itemfacturas/create"

  get "itemfacturas/edit"

  get "itemfacturas/update"

  get "itemfacturas/destroy"

  get "productos/index"

  get "productos/show"

  get "productos/new"

  get "productos/create"

  get "productos/edit"

  get "productos/update"

  get "productos/destroy"

  get "facturas/index"

  get "facturas/show"

  get "facturas/new"

  get "facturas/create"

  get "facturas/edit"

  get "facturas/update"

  get "facturas/destroy"

  get "clientes/index"

  get "clientes/show"

  get "clientes/new"

  get "clientes/create"

  get "clientes/edit"

  get "clientes/update"

  get "clientes/destroy"

  get "facturas/autocomplete_cliente_cedula"

  resources :clientes
  resources :facturas
  resources :itemfacturas
  resources :productos

  resources :facturas do
    get :autocomplete_cliente_cedula, :on => :collection
  end

  

  root :to => 'productos#index'

end

app/models/producto.rb
# encoding: utf-8
class Producto < ActiveRecord::Base
  attr_accessor :proveedor_producto

  attr_accessible :descripcion, :precio, :stock, :fecha_caducidad, :tipo, :proveedor_id, :proveedor_producto
  has_many :itemfacturas
  has_many :facturas, :through => :itemfacturas
  validates :descripcion, :precio, :stock, :fecha_caducidad, :tipo, :presence => true 
  validates :descripcion, :uniqueness => { :message => "Elija otra descripción" }
  belongs_to :proveedor

  def self.search(search)
  	if search
  		where('descripcion LIKE ?', "%#{search}%")
  	else
  		scoped
  	end
  	
  end

end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    respond_to do |format|
        format.html {    
        presentacion
        }
       format.js{
        presentacion       
      }
        format.json { 
          @productos = Producto.where("descripcion like ?", "%#{params[:term]}%")
          @productos = @productos.map do |producto|
            {
              :id => producto.id,
              :label => producto.descripcion,
              :value => producto.descripcion,
              :precio => producto.precio
            }
          end
          render :json => @productos 
        }
      end
  end

  def show
    @producto = Producto.find(params[:id])
  end

  def new
    @producto = Producto.new
  end

  def create
    @producto = Producto.new(params[:producto])
    if @producto.save
      redirect_to productos_path, :notice => "Producto guardado"
    else
      render "new"
    end
  end

  def edit
    @producto = Producto.find(params[:id])
  end

  def update
    @producto = Producto.find(params[:id])
  
  if @producto.update_attributes(params[:producto]) 
    redirect_to productos_path, :notice => "Producto actualizado"
  else
    render "edit"
  end
  end

  def destroy
    @producto = Producto.find(params[:id])
    @producto.destroy
    redirect_to productos_path, :notice => "Producto eliminado"
  end

  private

  def sort_column
    Producto.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def presentacion
    @productos = Producto.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 10)
  end

end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for @producto do |f| %>
	<% if @producto.errors.any? %>
		<h2>Errores:</h2>	
		<ul>
			<% @producto.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
<br>
	<%= f.label :descripcion, "Descripción" %>
	<%= f.text_area :descripcion, :size => "2x3", :required => true %><br />
<br />
	<%= f.label :stock, "Stock" %>
	<%= f.number_field :stock , :min => 0, :required => true %>
	<br />
	<%= f.label :precio, "Precio" %>
	<%= f.number_field :precio, :step => "any", :required => true%>
	<br />
	<%= f.label :tipo, "Tipo de producto" %>
	<%= f.text_field :tipo, :step => "any", :required => true%>
	<br />
	<%= f.label :proveedor_producto, "Proveedor" %>
	<%= f.text_field :proveedor_producto, :step => "any", :required => true%>
	<%= f.hidden_field :proveedor_id, :step => "any", :required => true%>
	<br />
	<%= f.label :fecha_caducidad, "Fecha de Caducidad" %>
	<%= f.date_select :fecha_caducidad, :step => "any", :required => true%>

<p>
	<%if @producto.new_record?%>
		<%= f.submit "Crear Producto", :class => "btn btn-success" %>
	<%else%>
		<%= f.submit "Actualizar Producto", :class => "btn btn-success" %>
	<%end%>
</p>
<% end %>

app/views/productos/_productos.html.erb
<%= hidden_field_tag :direction, params[:direction]%>
<%= hidden_field_tag :sort, params[:sort]%>
<table class="table table-striped">
    <tr>
      <th><%=sortable "id", "Código"%></th>
      <th><%=sortable "descripcion" %></th>
      <th><%=sortable  "stock" %></th>
      <th><%=sortable  "precio" %></th>
      <th><%=sortable  "tipo" %></th>
      <th><%=sortable  "proveedor" %></th>
      <th><%=sortable "fecha_caducidad"%></th>      
      <th>Acciones</th>
    </tr>
    <% @productos.each do |producto| %>
    <tr>
      <td><%= producto.id %></td>
      <td><%= producto.descripcion %></td>
      <td><%= producto.stock %></td>
      <td><%= producto.precio %></td>
      <td><%= producto.tipo %></td>
      <td><%= producto.proveedor.nombres if not producto.proveedor.blank? %></td>
      <td><%= producto.fecha_caducidad.strftime("%Y-%m-%d") if producto.fecha_caducidad? %></td>
      <td><%= link_to "Mostrar", {:action => "show", :id => producto} , :class => 'btn btn-mini btn-info'%> | <%= link_to "Editar", edit_producto_path(producto),:class => 'btn btn-mini' %> | 
<%= link_to "Borrar", producto, :confirm => "Estas seguro?", :method => :delete , :class => 'btn btn-mini btn-danger'%></td>
    </tr>
    <% end %>
  </table>
  <%= will_paginate @productos%>

app/views/productos/edit.html.erb
<h1>Productos</h1>
<h2>Editar Productos</h2>
 
<%= render 'form' %>

app/views/productos/index.html.erb
<h1> Productos </h1>
<h2>Listado productos</h2>

<%= form_tag productos_path, :method => 'get', :id => "products_search", :remote => true do%>
  <p>
  <%= text_field_tag :search, params[:search], :placeholder => "Buscar por descripción"%>
   </p>
   <div id="productos"><%= render 'productos' %></div>
<%end%>
<p><%= link_to "Agregar nuevo producto", new_producto_path,:class => 'btn btn-primary' %></p> 

app/views/productos/index.js.erb
$("#productos").html("<%= escape_javascript(render("productos")) %>")

app/views/productos/new.html.erb
<h1>Productos</h1>
<h2>Nuevo producto</h2>
 
<%= render 'form' %>

app/views/productos/show.html.erb
<h1>Productos</h1>
<h2>Mostrar producto</h2>

<div class="info_title">Descripción:</div>
	<div class="info_content"><%=@producto.descripcion%></div>
<div class="info_title">Stock:</div>
	<div class="info_content"><%=@producto.stock%></div>
<div class="info_title">Precio:</div>
	<div class="info_content"><%=@producto.precio%></div>

<%= link_to "Regresar a la lista", { :controller => :productos}, :class => "btn btn-inverse"%>