config/routes.rb
Facturacion::Application.routes.draw do
 

  resources :proveedors

  get "itemfacturas/index"

  get "itemfacturas/show"

  get "itemfacturas/new"

  get "itemfacturas/create"

  get "itemfacturas/edit"

  get "itemfacturas/update"

  get "itemfacturas/destroy"

  get "productos/index"

  get "productos/show"

  get "productos/new"

  get "productos/create"

  get "productos/edit"

  get "productos/update"

  get "productos/destroy"

  get "facturas/index"

  get "facturas/show"

  get "facturas/new"

  get "facturas/create"

  get "facturas/edit"

  get "facturas/update"

  get "facturas/destroy"

  get "clientes/index"

  get "clientes/show"

  get "clientes/new"

  get "clientes/create"

  get "clientes/edit"

  get "clientes/update"

  get "clientes/destroy"

  get "facturas/autocomplete_cliente_cedula"

  resources :clientes
  resources :facturas
  resources :itemfacturas
  resources :productos

  resources :facturas do
    get :autocomplete_cliente_cedula, :on => :collection
  end

  

  root :to => 'productos#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Facturacion</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application",:media => "all"%>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/facturas/new">Facturación</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Facturas" , facturas_path %></li>
          <li><%= link_to "Productos", productos_path %></li>
          <li><%= link_to "Clientes" , clientes_path%></li>
          <li><%= link_to "Proveedores" , proveedors_path%></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div id="alerts">
  <% if flash[:alert] %>
    <p class="flash-error"><%= flash[:alert] %></p>
  <% end %>
  <% if flash[:notice] %>
    <p class="flash-notice"><%= flash[:notice] %></p>
  <% end %>
</div>

<div class="container">
	<div class="rows">
		<div class="span12"><%= yield %></div>
		
	</div>
</div>
</body>
</html>